apiVersion: v2
name: castai-aio
description: CAST AI All In One (AIO) deployment chart.
type: application
version: 0.0.1

dependencies:
  - name: castai-agent
    version: 0.111.0
    repository: https://castai.github.io/helm-charts
    condition: castai-agent.enabled
    #import-values:
    #  - child: "settings"
    #    parent: global
  - name: castai-cluster-controller
    version: 0.82.2
    repository: https://castai.github.io/helm-charts
    condition: castai-cluster-controller.enabled
    import-values:
      - child: castai
        parent: global
  - name: castai-workload-autoscaler
    version: 0.1.118
    repository: https://castai.github.io/helm-charts
    condition: castai-workload-autoscaler.enabled
    import-values:
      - child: castai
        parent: global
  - name: castai-evictor
    version: 0.33.34
    repository: https://castai.github.io/helm-charts
    condition: castai-evictor.enabled
  - name: castai-pod-mutator
    version: 0.0.38
    repository: https://castai.github.io/helm-charts
    condition: castai-pod-mutator.enabled
    import-values:
      - child: castai
        parent: global
  - name: castai-spot-handler
    version: 0.26.4
    repository: https://castai.github.io/helm-charts
    condition: castai-spot-handler.enabled
    import-values:
      - child: castai
        parent: global