---
global:
  apiUrl: "https://api.cast.ai"
  apiKey: ""
  apiKeySecretRef: "castai-aio"
  clusterIdSecretKeyRef: 
    name: "castai-aio"
  eks:
    region: ""
    accountNumber: ""
    credentials:
      accessKeyId: "YOUR_AWS_ACCESS_KEY_ID"
      secretAccessKey: "YOUR_AWS_SECRET_ACCESS_KEY"
      sessionToken: ""  # optional

castai-agent:
  enabled: true
  apiUrl: "https://api.cast.ai"
  createNamespace: false
  provider: ""
  additionalEnv:
    ANYWHERE_CLUSTER_NAME: ""
  metadataStore:
    enabled: true

castai-cluster-controller:
  enabled: true
  replicas: 2
  pdbMinAvailable: 1
  castai:
    apiKeySecretRef: "castai-aio"
    clusterIdSecretKeyRef: 
      name: "castai-aio"
  enableTopologySpreadConstraints: true

castai-workload-autoscaler:
  enabled: true
  castai:
    apiKeySecretRef: "castai-aio"
    clusterIdSecretKeyRef: 
      name: "castai-aio"
  nameOverride: "castai-workload-autoscaler"

castai-evictor:
  enabled: true
  replicaCount: 1
  apiKeySecretRef: "castai-aio"
  clusterIdSecretKeyRef: 
    name: "castai-aio"

castai-pod-mutator:
  enabled: true
  castai:
    apiKeySecretRef: "castai-aio"
    clusterIdSecretKeyRef: 
      name: "castai-aio"

castai-spot-handler:
  enabled: true
  castai:
    provider: ""
    apiKeySecretRef: "castai-aio"
    clusterIdSecretKeyRef: 
      name: "castai-aio"

infrastructureAutoscaling:
  enabled: false

helper:
  image:
    repository: docker.io/kisahm/castai-aio-helper
    tag: v0.0.17
  debug: false