---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-get-credentials
  namespace: castai-agent
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: helper
        image: {{.Values.helper.image.repository}}:{{.Values.helper.image.tag}}
        command: ["/get-credentials.sh"]
        imagePullPolicy: Always
        env:
          - name: CASTAI_CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: castai-agent-metadata
                key: CLUSTER_ID
          - name: NAMESPACE
            value: "castai-agent"
          - name: SECRET_NAME
            value: "{{.Values.global.apiKeySecretRef}}"
          - name: CASTAI_API_TOKEN
            value: "{{.Values.global.apiKey}}"
          - name: CASTAI_API_URL
            value: "{{.Values.global.apiUrl}}"
{{- if eq .Values.helper.debug true }}
          - name: DEBUG
            value: "true"
{{- end }}
      restartPolicy: Never
      serviceAccountName: castai-aio-helper
  backoffLimit: 4