---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-aio-helper
  namespace: castai-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: castai-aio-helper
  namespace: castai-agent
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: castai-aio-helper-binding
  namespace: castai-agent
subjects:
  - kind: ServiceAccount
    name: castai-aio-helper
    namespace: castai-agent
roleRef:
  kind: Role
  name: castai-aio-helper
  apiGroup: rbac.authorization.k8s.io