{{- if and (eq (index .Values "castai-agent" "provider") "eks") (eq (index .Values "infrastructureAutoscaling" "enabled") true) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: "castai-agent"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.global.eks.credentials.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.eks.credentials.secretAccessKey | b64enc }}
  {{- if .Values.global.eks.credentials.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.global.eks.credentials.sessionToken | b64enc }}
  {{- end }}
{{- end }}
